repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude: ([a-zA-Z0-9])+(.mustache)$
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-xml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or:
          - markdown
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
