apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/Alfresco/alfresco-process-acceptance-tests
        - https://github.com/Alfresco/alfresco-process-releases
      reusePullRequest: true
      changes:
        - regex:
            pattern: "<alfresco-process-sdk.version>(.*)</alfresco-process-sdk.version>"
            files:
              - pom.xml
