name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@c2ebfbb418295b18eca057303a5881324be0de42 # v8.6.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
