name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@a809e68fae7ded4c8ad28bb2fd463187cd28bc34 # v8.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
