name: Cleanup caches for work branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/gh-cache-cleanup-on-merge@c0fa39de055c31c2b9abb96fd1030260c6ed34ea # v7.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
