name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@21fb2cdff9e78dae9d11604252d778c2f1af8a43 # v7.1.1
        with:
          jira-project-key: AAE|HXOR
          valid-branch-regex: ^(revert-|(improvement|fix|feature|test|tmp|release)\/(AAE|HXOR)-[0-9]+[_-]{1}[A-Za-z0-9._-]+|release\/[A-Za-z0-9]+)$
          whitelist-branches: |-
            release/*
